/**
 * 01-onboarding.spec.ts
  *
   * SUITE: Company Sign-Up & Onboarding
    *
     * Tests the complete company registration flow:
      *   1. API health check — confirms the server is up
       *   2. Duplicate email rejection — tries to re-register with same email
        *   3. Password validation — short password is rejected
         *   4. UI onboarding form — fills /onboard page, submits, and confirms redirect to dashboard
          *   5. Auto-login — verifies hf_token is stored in localStorage after signup
           *   6. Token structure — verifies token contains correct payload
            *   7. Duplicate email via UI — shows error message, not redirect
             *
              * After this suite the .test-context.json will have:
               *   adminToken, companyId, adminEmail, adminPassword
                */

                import { test, expect } from '@playwright/test';
                import { loadContext, saveContext, apiRequest } from './helpers';

                test.describe('Company Sign-Up & Onboarding', () => {

                  test('01 - API health check', async ({ request }) => {
                      const ctx = loadContext();
                          const res = await request.get(`${ctx.baseUrl}/api/health`);
                              expect(res.ok()).toBeTruthy();
                                  const body = await res.json();
                                      expect(body.status).toBe('ok');
                                          expect(body.service).toBe('HaulFlow API');
                                            });

                                              test('02 - Rejects missing required fields via API', async ({ request }) => {
                                                  const ctx = loadContext();
                                                      const res = await request.post(`${ctx.baseUrl}/api/onboard`, {
                                                            data: { company_name: 'Incomplete Co' },
                                                                });
                                                                    expect(res.status()).toBe(400);
                                                                        const body = await res.json();
                                                                            expect(body.error).toBeTruthy();
                                                                              });

                                                                                test('03 - Rejects password shorter than 6 characters via API', async ({ request }) => {
                                                                                    const ctx = loadContext();
                                                                                        const res = await request.post(`${ctx.baseUrl}/api/onboard`, {
                                                                                              data: {
                                                                                                      company_name: 'Short Pass Co',
                                                                                                              admin_name: 'Test Admin',
                                                                                                                      admin_email: `short${Date.now()}@test.com`,
                                                                                                                              password: '123',
                                                                                                                                    },
                                                                                                                                        });
                                                                                                                                            expect(res.status()).toBe(400);
                                                                                                                                                const body = await res.json();
                                                                                                                                                    expect(body.error).toMatch(/password/i);
                                                                                                                                                      });
                                                                                                                                                      
                                                                                                                                                        test('04 - Successfully creates a new trucking company via API', async ({ request }) => {
                                                                                                                                                            const ctx = loadContext();
                                                                                                                                                            
                                                                                                                                                                const res = await request.post(`${ctx.baseUrl}/api/onboard`, {
                                                                                                                                                                      data: {
                                                                                                                                                                              company_name: ctx.companyName,
                                                                                                                                                                                      company_email: `billing@thunderridge${Date.now()}.test`,
                                                                                                                                                                                              company_phone: '615-555-0100',
                                                                                                                                                                                                      mc_number: 'MC-998877',
                                                                                                                                                                                                              dot_number: '3344556',
                                                                                                                                                                                                                      admin_name: 'Kevin Thunder',
                                                                                                                                                                                                                              admin_email: ctx.adminEmail,
                                                                                                                                                                                                                                      password: ctx.adminPassword,
                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    expect(res.ok(), `Onboard API failed: ${await res.text()}`).toBeTruthy();
                                                                                                                                                                                                                                                        const body = await res.json();
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            // Verify response structure
                                                                                                                                                                                                                                                                expect(body.token).toBeTruthy();
                                                                                                                                                                                                                                                                    expect(body.user).toBeTruthy();
                                                                                                                                                                                                                                                                        expect(body.user.email).toBe(ctx.adminEmail);
                                                                                                                                                                                                                                                                            expect(body.user.role).toBe('admin');
                                                                                                                                                                                                                                                                                expect(body.company).toBeTruthy();
                                                                                                                                                                                                                                                                                    expect(body.company.name).toBe(ctx.companyName);
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                        // Save to context for subsequent specs
                                                                                                                                                                                                                                                                                            saveContext({
                                                                                                                                                                                                                                                                                                  adminToken: body.token,
                                                                                                                                                                                                                                                                                                        companyId: body.company.id,
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                test('05 - Rejects duplicate email registration via API', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                    const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                        const res = await request.post(`${ctx.baseUrl}/api/onboard`, {
                                                                                                                                                                                                                                                                                                                              data: {
                                                                                                                                                                                                                                                                                                                                      company_name: 'Duplicate Co',
                                                                                                                                                                                                                                                                                                                                              admin_name: 'Dup Admin',
                                                                                                                                                                                                                                                                                                                                                      admin_email: ctx.adminEmail, // same email as just registered
                                                                                                                                                                                                                                                                                                                                                              password: 'validpass123',
                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                            expect(res.status()).toBe(409);
                                                                                                                                                                                                                                                                                                                                                                                const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                    expect(body.error).toMatch(/already exists/i);
                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                        test('06 - Token contains correct payload structure', async () => {
                                                                                                                                                                                                                                                                                                                                                                                            const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                expect(ctx.adminToken).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    const parts = ctx.adminToken.split('.');
                                                                                                                                                                                                                                                                                                                                                                                                        expect(parts.length).toBe(3);
                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                            const payload = JSON.parse(Buffer.from(parts[1], 'base64').toString());
                                                                                                                                                                                                                                                                                                                                                                                                                expect(payload.email).toBe(ctx.adminEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                    expect(payload.role).toBe('admin');
                                                                                                                                                                                                                                                                                                                                                                                                                        expect(payload.company_id).toBe(ctx.companyId);
                                                                                                                                                                                                                                                                                                                                                                                                                            expect(payload.user_id).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                test('07 - UI: /onboard page loads and shows the signup form', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                    const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                        await page.goto(`${ctx.baseUrl}/onboard`);
                                                                                                                                                                                                                                                                                                                                                                                                                                            await expect(page.locator('text=HaulFlow')).toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                                                                                await expect(page.locator('input[placeholder*="ABC Trucking" i], input[placeholder*="Company Name" i]').first()).toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    await expect(page.locator('input[type="password"]').first()).toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                                                                                        await expect(page.locator('button[type="submit"], button:has-text("Create Account")')).toBeVisible();
                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                            test('08 - UI: /onboard shows error for duplicate email', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await page.goto(`${ctx.baseUrl}/onboard`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await page.waitForLoadState('networkidle');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Fill company info
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await page.locator('input[placeholder*="ABC Trucking" i], input[placeholder*="Company" i]').first().fill('Dup Test Co');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await page.locator('input[placeholder*="John Smith" i], input[placeholder*="Your Name" i]').first().fill('Dup Admin');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Fill email inputs — find the admin email field specifically
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const emailInputs = page.locator('input[type="email"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await emailInputs.last().fill(ctx.adminEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Fill password
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const passwordInputs = page.locator('input[type="password"]');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await passwordInputs.first().fill(ctx.adminPassword);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await passwordInputs.last().fill(ctx.adminPassword);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await page.click('button[type="submit"], button:has-text("Create Account")');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Should show error message, not redirect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await expect(page.locator('text=already exists, text=account with that email')).toBeVisible({ timeout: 10_000 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(page.url()).toContain('/onboard');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    test('09 - UI: Successful onboard redirects to dashboard (new unique email)', async ({ page }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const uniqueSuffix = Date.now().toString().slice(-5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const newEmail = `newadmin${uniqueSuffix}@thunderridge.test`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const newCompany = `Thunder Ridge #{uniqueSuffix}`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await page.goto(`${ctx.baseUrl}/onboard`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await page.waitForLoadState('networkidle');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await page.locator('input[placeholder*="ABC Trucking" i], input[placeholder*="Company" i]').first().fill(newCompany);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await page.locator('input[placeholder*="John Smith" i], input[placeholder*="Your Name" i]').first().fill('New Admin');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        await page.locator('input[type="email"]').last().fill(newEmail);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await page.locator('input[type="password"]').first().fill('TestPass123!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                await page.locator('input[type="password"]').last().fill('TestPass123!');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await page.click('button[type="submit"], button:has-text("Create Account")');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Should redirect to dashboard or show success message
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            await page.waitForTimeout(3000);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const isSuccess =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      page.url() === `${ctx.baseUrl}/` ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            page.url().endsWith('/') ||
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  await page.locator("text=You're in, text=account is ready, text=Dashboard").first().isVisible().catch(() => false);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expect(isSuccess, `Expected success or redirect but URL was ${page.url()}`).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
