/**
 * 04-driver-portal.spec.ts
  *
   * SUITE: Driver Mobile Portal
    *
     * Tests the driver-facing API (used by the React Native mobile app):
      *   1. Driver login by phone — POST /api/auth/driver-login
       *   2. Driver login rejects wrong password
        *   3. Driver login rejects unknown phone
         *   4. Driver can fetch their assigned loads
          *   5. Driver can update load status (pickup, in_transit, delivered)
           *   6. Driver login by phone without password (legacy mode)
            *   7. GET /api/driver/dvir/today returns null initially
             *   8. POST /api/driver/dvir/submit — submits a full pre-trip inspection (all pass)
              *   9. POST /api/driver/dvir/submit — submits inspection with one defect
               *  10. GET /api/driver/dvir/today returns the inspection after submit
                */

                import { test, expect } from '@playwright/test';
                import { loadContext, saveContext } from './helpers';

                let driverToken = '';

                test.describe('Driver Portal', () => {

                  test('01 - Driver login returns token', async ({ request }) => {
                      const ctx = loadContext();
                          const res = await request.post(ctx.baseUrl + '/api/auth/driver-login', {
                                data: { phone: ctx.driverPhone, password: ctx.driverPassword },
                                    });
                                        expect(res.ok(), 'Driver login failed: ' + JSON.stringify(await res.json().catch(() => {}))).toBeTruthy();
                                            const body = await res.json();
                                                expect(body.token).toBeTruthy();
                                                    expect(body.driver.name).toBe('Bobby Roadhog');
                                                        driverToken = body.token;
                                                            saveContext({ driverToken: body.token } as any);
                                                              });

                                                                test('02 - Driver login rejects wrong password', async ({ request }) => {
                                                                    const ctx = loadContext();
                                                                        const res = await request.post(ctx.baseUrl + '/api/auth/driver-login', {
                                                                              data: { phone: ctx.driverPhone, password: 'wrongpassword' },
                                                                                  });
                                                                                      expect(res.status()).toBe(401);
                                                                                        });

                                                                                          test('03 - Driver login rejects unknown phone', async ({ request }) => {
                                                                                              const ctx = loadContext();
                                                                                                  const res = await request.post(ctx.baseUrl + '/api/auth/driver-login', {
                                                                                                        data: { phone: '0000000000', password: 'anypass' },
                                                                                                            });
                                                                                                                expect(res.status()).toBe(401);
                                                                                                                  });
                                                                                                                  
                                                                                                                    test('04 - Driver can fetch assigned loads', async ({ request }) => {
                                                                                                                        const ctx = loadContext();
                                                                                                                            const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                const res = await request.get(ctx.baseUrl + '/api/driver/loads', {
                                                                                                                                      headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                          });
                                                                                                                                              expect(res.ok()).toBeTruthy();
                                                                                                                                                  const body = await res.json();
                                                                                                                                                      expect(Array.isArray(body)).toBeTruthy();
                                                                                                                                                          // The load we created and assigned to this driver should appear
                                                                                                                                                              const load = body.find((l) => l.id === ctx.loadId);
                                                                                                                                                                  expect(load).toBeTruthy();
                                                                                                                                                                    });
                                                                                                                                                                    
                                                                                                                                                                      test('05 - Driver can update load status to picked_up', async ({ request }) => {
                                                                                                                                                                          const ctx = loadContext();
                                                                                                                                                                              const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                  const res = await request.patch(ctx.baseUrl + '/api/driver/loads/' + ctx.loadId + '/status', {
                                                                                                                                                                                        headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                              data: { status: 'in_transit' },
                                                                                                                                                                                                  });
                                                                                                                                                                                                      expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                          const body = await res.json();
                                                                                                                                                                                                              expect(body.status).toBe('in_transit');
                                                                                                                                                                                                                });
                                                                                                                                                                                                                
                                                                                                                                                                                                                  test('06 - Driver can mark load as delivered', async ({ request }) => {
                                                                                                                                                                                                                      const ctx = loadContext();
                                                                                                                                                                                                                          const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                                                              const res = await request.patch(ctx.baseUrl + '/api/driver/loads/' + ctx.loadId + '/status', {
                                                                                                                                                                                                                                    headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                                                                          data: { status: 'delivered' },
                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                  expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                      const body = await res.json();
                                                                                                                                                                                                                                                          expect(body.status).toBe('delivered');
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                              test('07 - GET /api/driver/dvir/today returns null initially', async ({ request }) => {
                                                                                                                                                                                                                                                                  const ctx = loadContext();
                                                                                                                                                                                                                                                                      const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                                                                                                          const res = await request.get(ctx.baseUrl + '/api/driver/dvir/today', {
                                                                                                                                                                                                                                                                                headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                        // May return null or an existing inspection — just check it does not 500
                                                                                                                                                                                                                                                                                            expect(res.status()).not.toBe(500);
                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                test('08 - Driver submits pre-trip inspection (all pass)', async ({ request }) => {
                                                                                                                                                                                                                                                                                                    const ctx = loadContext();
                                                                                                                                                                                                                                                                                                        const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                                                                                                                                            const res = await request.post(ctx.baseUrl + '/api/driver/dvir/submit', {
                                                                                                                                                                                                                                                                                                                  headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                                                                                                                                                        data: {
                                                                                                                                                                                                                                                                                                                                truck_unit: 'T-101',
                                                                                                                                                                                                                                                                                                                                        items: [
                                                                                                                                                                                                                                                                                                                                                  { category: 'Tires & Wheels', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                            { category: 'Brakes', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                      { category: 'Lights & Reflectors', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                { category: 'Horn', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                          { category: 'Windshield & Wipers', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                    { category: 'Mirrors', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                              { category: 'Steering', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                        { category: 'Coupling Devices', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                  { category: 'Emergency Equipment', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                            { category: 'Fuel System', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                          },
                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(body.success).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(body.inspection.overall_status).toBe('pass');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  expect(body.inspection.has_defects).toBeFalsy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      test('09 - Driver submits inspection with defect (fail)', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const res = await request.post(ctx.baseUrl + '/api/driver/dvir/submit', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      truck_unit: 'T-101',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              items: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { category: 'Tires & Wheels', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  { category: 'Brakes', status: 'fail', notes: 'Left rear brake feels soft' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { category: 'Lights & Reflectors', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { category: 'Horn', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { category: 'Windshield & Wipers', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { category: 'Mirrors', status: 'pass', notes: '' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expect(body.inspection.overall_status).toBe('fail');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            expect(body.inspection.has_defects).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                test('10 - GET /api/driver/dvir/today returns submitted inspection', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const tkn = (ctx as any).driverToken || driverToken;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const res = await request.get(ctx.baseUrl + '/api/driver/dvir/today', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  headers: { Authorization: 'Bearer ' + tkn },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Should have a recent inspection (submitted in test 08 or 09)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expect(body.inspection).not.toBeNull();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(body.inspection.truck_unit).toBe('T-101');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              test('11 - Unauthorized driver request is rejected', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const res = await request.get(ctx.baseUrl + '/api/driver/loads');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(res.status()).toBe(401);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
