/**
 * 05-invoicing.spec.ts
  *
   * SUITE: Invoice Generation and Payment
    *
     * Tests the full invoice lifecycle:
      *   1. Create an invoice linked to a delivered load + customer
       *   2. Verify invoice number is auto-generated (TRL-XXXXX format)
        *   3. List invoices — returns the created invoice
         *   4. Invoice status starts as 'unpaid'
          *   5. Mark invoice as paid — PATCH /api/invoices/:id/pay
           *   6. Paid invoice shows in paid list with paid_at timestamp
            *   7. Create multiple invoices and verify counter increments
             *   8. Invoice amount matches load rate
              */

              import { test, expect } from '@playwright/test';
              import { loadContext, saveContext } from './helpers';

              test.describe('Invoicing', () => {

                test('01 - POST /api/invoices creates invoice with auto-generated number', async ({ request }) => {
                    const ctx = loadContext();
                        const dueDate = new Date();
                            dueDate.setDate(dueDate.getDate() + 30);
                                const dueDateStr = dueDate.toISOString().split('T')[0];

                                    const res = await request.post(ctx.baseUrl + '/api/invoices', {
                                          headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                data: {
                                                        customer_id: ctx.customerId,
                                                                load_id: ctx.loadId,
                                                                        amount: 2850.00,
                                                                                due_date: dueDateStr,
                                                                                        notes: 'Detroit to Chicago steel haul',
                                                                                              },
                                                                                                  });

                                                                                                      expect(res.ok()).toBeTruthy();
                                                                                                          const body = await res.json();
                                                                                                              expect(body.id).toBeTruthy();
                                                                                                                  expect(body.invoice_number).toBeTruthy();
                                                                                                                      expect(body.invoice_number).toMatch(/^TRL-\d+$/);
                                                                                                                          expect(body.status).toBe('unpaid');
                                                                                                                              expect(parseFloat(body.amount)).toBe(2850);
                                                                                                                                  saveContext({ invoiceId: body.id });
                                                                                                                                    });
                                                                                                                                    
                                                                                                                                      test('02 - GET /api/invoices returns invoice list', async ({ request }) => {
                                                                                                                                          const ctx = loadContext();
                                                                                                                                              const res = await request.get(ctx.baseUrl + '/api/invoices', {
                                                                                                                                                    headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                        });
                                                                                                                                                            expect(res.ok()).toBeTruthy();
                                                                                                                                                                const body = await res.json();
                                                                                                                                                                    expect(Array.isArray(body)).toBeTruthy();
                                                                                                                                                                        const invoice = body.find((i) => i.id === ctx.invoiceId);
                                                                                                                                                                            expect(invoice).toBeTruthy();
                                                                                                                                                                                expect(invoice.customer_name).toBe('Midwest Steel Corp');
                                                                                                                                                                                  });
                                                                                                                                                                                  
                                                                                                                                                                                    test('03 - Invoice is initially unpaid', async ({ request }) => {
                                                                                                                                                                                        const ctx = loadContext();
                                                                                                                                                                                            const res = await request.get(ctx.baseUrl + '/api/invoices', {
                                                                                                                                                                                                  headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                                                                      });
                                                                                                                                                                                                          expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                              const body = await res.json();
                                                                                                                                                                                                                  const invoice = body.find((i) => i.id === ctx.invoiceId);
                                                                                                                                                                                                                      expect(invoice.status).toBe('unpaid');
                                                                                                                                                                                                                          expect(invoice.paid_at).toBeFalsy();
                                                                                                                                                                                                                            });
                                                                                                                                                                                                                            
                                                                                                                                                                                                                              test('04 - PATCH /api/invoices/:id/pay marks invoice as paid', async ({ request }) => {
                                                                                                                                                                                                                                  const ctx = loadContext();
                                                                                                                                                                                                                                      const res = await request.patch(ctx.baseUrl + '/api/invoices/' + ctx.invoiceId + '/pay', {
                                                                                                                                                                                                                                            headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                    expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                        const body = await res.json();
                                                                                                                                                                                                                                                            expect(body.status).toBe('paid');
                                                                                                                                                                                                                                                                expect(body.paid_at).toBeTruthy();
                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                    test('05 - Invoice shows as paid after payment', async ({ request }) => {
                                                                                                                                                                                                                                                                        const ctx = loadContext();
                                                                                                                                                                                                                                                                            const res = await request.get(ctx.baseUrl + '/api/invoices', {
                                                                                                                                                                                                                                                                                  headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                          expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                              const body = await res.json();
                                                                                                                                                                                                                                                                                                  const invoice = body.find((i) => i.id === ctx.invoiceId);
                                                                                                                                                                                                                                                                                                      expect(invoice.status).toBe('paid');
                                                                                                                                                                                                                                                                                                          expect(invoice.paid_at).toBeTruthy();
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              test('06 - Create second invoice and verify counter increments', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                  const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                      const res = await request.post(ctx.baseUrl + '/api/invoices', {
                                                                                                                                                                                                                                                                                                                            headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                                                                                                                                                                                                  data: {
                                                                                                                                                                                                                                                                                                                                          customer_id: ctx.customerId,
                                                                                                                                                                                                                                                                                                                                                  amount: 1950.00,
                                                                                                                                                                                                                                                                                                                                                          due_date: '2026-08-15',
                                                                                                                                                                                                                                                                                                                                                                  notes: 'Memphis to Atlanta auto parts',
                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                    const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                        expect(body.invoice_number).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                            expect(body.invoice_number).toMatch(/^TRL-\d+$/);
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                // Extract counter numbers and verify second is greater
                                                                                                                                                                                                                                                                                                                                                                                                    const firstNum = parseInt(ctx.invoiceId ? body.invoice_number.split('-')[1] : '0');
                                                                                                                                                                                                                                                                                                                                                                                                        expect(firstNum).toBeGreaterThan(0);
                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                            test('07 - Invoice without load_id is allowed', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                    const res = await request.post(ctx.baseUrl + '/api/invoices', {
                                                                                                                                                                                                                                                                                                                                                                                                                          headers: { Authorization: 'Bearer ' + ctx.adminToken },
                                                                                                                                                                                                                                                                                                                                                                                                                                data: {
                                                                                                                                                                                                                                                                                                                                                                                                                                        customer_id: ctx.customerId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                amount: 500.00,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        due_date: '2026-09-01',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                notes: 'Detention charges',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expect(res.ok()).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const body = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      expect(body.id).toBeTruthy();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(body.status).toBe('unpaid');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              test('08 - Unauthorized request to invoices is rejected', async ({ request }) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const ctx = loadContext();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const res = await request.get(ctx.baseUrl + '/api/invoices');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          expect(res.status()).toBe(401);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
